# Generated by Django 5.2.14 on 2026-05-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classinfo',
            options={'verbose_name': '班级', 'verbose_name_plural': '班级'},
        ),
        migrations.AlterField(
            model_name='classinfo',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='班级名称'),
        ),
    ]
