# Generated by Django 5.2.14 on 2026-05-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_classinfo_options_alter_classinfo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classinfo',
            name='name',
            field=models.CharField(help_text='班级名称，必须唯一，如"三年级1班"', max_length=50, unique=True, verbose_name='班级名称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', '管理员'), ('teacher', '教师'), ('student', '学生')], default='student', help_text='用户角色：admin=管理员，teacher=教师，student=学生', max_length=10, verbose_name='角色'),
        ),
    ]
