# Generated by Django 5.2.14 on 2026-05-11 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.CharField(max_length=100, unique=True, verbose_name='试卷唯一ID')),
                ('title', models.CharField(max_length=200, verbose_name='试卷标题')),
                ('subject', models.CharField(choices=[('math', '数学'), ('science', '科学')], max_length=10, verbose_name='学科')),
                ('visible_date', models.DateField(verbose_name='可见日期')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WrongQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answer', models.JSONField(verbose_name='做错时的答案')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_id', models.CharField(max_length=20, verbose_name='题目编号')),
                ('q_type', models.CharField(choices=[('multiple_choice', '选择题'), ('fill_in_blank', '填空题'), ('true_or_false', '判断题'), ('drawing', '画图题'), ('essay', '论述题')], max_length=20)),
                ('stem', models.TextField(verbose_name='题干(HTML)')),
                ('answer_data', models.JSONField(verbose_name='标准答案数据')),
                ('blank_configs', models.JSONField(blank=True, null=True, verbose_name='填空配置')),
                ('options', models.JSONField(blank=True, null=True, verbose_name='选项数据')),
                ('analysis', models.TextField(blank=True, verbose_name='解析')),
                ('knowledge_point', models.CharField(blank=True, max_length=100, verbose_name='知识点')),
                ('exam_point', models.CharField(blank=True, max_length=100, verbose_name='考查点')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='题目顺序')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answers', models.JSONField(verbose_name='学生提交的答案')),
                ('total_scoreable', models.IntegerField(default=0, verbose_name='可判分总题数')),
                ('correct_count', models.IntegerField(default=0, verbose_name='答对题数')),
                ('empty_count', models.IntegerField(default=0, verbose_name='空值题数')),
                ('correct_rate', models.FloatField(default=0.0, verbose_name='正确率')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成(含画图题已读)')),
                ('submit_time', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
            ],
        ),
    ]
