# Generated by Django 5.2.14 on 2026-05-13 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='总分'),
        ),
    ]
