# Generated by Django 5.2.14 on 2026-05-13 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_submission_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wrongquestion',
            name='student_answer',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='学生答案'),
        ),
    ]
