# Generated by Django 5.2.14 on 2026-05-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_alter_wrongquestion_student_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='score',
        ),
        migrations.AddField(
            model_name='submission',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最后更新时间'),
        ),
        migrations.AddField(
            model_name='submission',
            name='wrong_count',
            field=models.IntegerField(default=0, verbose_name='答错题数'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='correct_rate',
            field=models.FloatField(default=0.0, verbose_name='正确率(0-1)'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submit_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='首次提交时间'),
        ),
    ]
