# Generated by Django 5.2.14 on 2026-05-21 11:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_remove_submission_score_submission_updated_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wrongquestion',
            unique_together={('student', 'question', 'exam')},
        ),
    ]
