# Generated by Django 5.2.14 on 2026-05-22 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_alter_wrongquestion_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-display_start_date'], 'verbose_name': '试卷', 'verbose_name_plural': '试卷'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order'], 'verbose_name': '题目', 'verbose_name_plural': '题目'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-submit_time'], 'verbose_name': '提交记录', 'verbose_name_plural': '提交记录'},
        ),
        migrations.AlterModelOptions(
            name='wrongquestion',
            options={'ordering': ['-created_at'], 'verbose_name': '错题', 'verbose_name_plural': '错题'},
        ),
        migrations.AddField(
            model_name='exam',
            name='display_end_date',
            field=models.DateField(default='2099-12-31', help_text='试卷结束对学生展示的日期（包含当天），过了这天学生就看不到了', verbose_name='展示结束日期'),
        ),
        migrations.AddField(
            model_name='exam',
            name='display_start_date',
            field=models.DateField(default='2024-01-01', help_text='试卷开始对学生展示的日期（包含当天）', verbose_name='展示开始日期'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_id',
            field=models.CharField(help_text='试卷的唯一标识符，用于导入和查询', max_length=100, unique=True, verbose_name='试卷唯一ID'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.CharField(choices=[('math', '数学'), ('science', '科学')], help_text='试卷所属学科', max_length=10, verbose_name='学科'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='title',
            field=models.CharField(help_text='试卷的显示名称', max_length=200, verbose_name='试卷标题'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='visible_date',
            field=models.DateField(blank=True, help_text='此字段已废弃，请使用展示开始日期和展示结束日期', null=True, verbose_name='可见日期（旧字段，已废弃）'),
        ),
        migrations.AlterField(
            model_name='question',
            name='analysis',
            field=models.TextField(blank=True, help_text='答案解析，显示在错题本中', verbose_name='解析'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_data',
            field=models.JSONField(help_text='JSON格式，选择题为字母，填空题为字典格式', verbose_name='标准答案数据'),
        ),
        migrations.AlterField(
            model_name='question',
            name='blank_configs',
            field=models.JSONField(blank=True, help_text='填空题专用配置，如 [{"blank_id": "b1", "is_ordered": true}]', null=True, verbose_name='填空配置'),
        ),
        migrations.AlterField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(help_text='这道题目属于哪张试卷', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam', verbose_name='所属试卷'),
        ),
        migrations.AlterField(
            model_name='question',
            name='exam_point',
            field=models.CharField(blank=True, help_text='题目考查的具体知识点', max_length=100, verbose_name='考查点'),
        ),
        migrations.AlterField(
            model_name='question',
            name='knowledge_point',
            field=models.CharField(blank=True, help_text='题目所属知识点，用于分类统计', max_length=100, verbose_name='知识点'),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, help_text='选择题的选项，如 {"A": "选项A", "B": "选项B"}', null=True, verbose_name='选项数据'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='题目在试卷中的显示顺序，数字越小越靠前', verbose_name='题目顺序'),
        ),
        migrations.AlterField(
            model_name='question',
            name='q_id',
            field=models.CharField(help_text='题目的唯一编号，如 q1, q2', max_length=20, verbose_name='题目编号'),
        ),
        migrations.AlterField(
            model_name='question',
            name='q_type',
            field=models.CharField(choices=[('multiple_choice', '选择题'), ('fill_in_blank', '填空题'), ('true_or_false', '判断题'), ('drawing', '画图题'), ('essay', '论述题')], max_length=20, verbose_name='题目类型'),
        ),
        migrations.AlterField(
            model_name='question',
            name='stem',
            field=models.TextField(help_text='题目内容，支持HTML格式', verbose_name='题干(HTML)'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='correct_count',
            field=models.IntegerField(default=0, help_text='学生答对的题目数量', verbose_name='答对题数'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='correct_rate',
            field=models.FloatField(default=0.0, help_text='答对题数除以可判分总题数，范围0-1', verbose_name='正确率(0-1)'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='empty_count',
            field=models.IntegerField(default=0, help_text='学生未作答的题目数量', verbose_name='空值题数'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='exam',
            field=models.ForeignKey(help_text='提交的试卷', on_delete=django.db.models.deletion.CASCADE, to='exams.exam', verbose_name='试卷'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='标记学生是否已完成整张试卷', verbose_name='是否完成(含画图题已读)'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(help_text='提交试卷的学生', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='学生'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='student_answers',
            field=models.JSONField(help_text='JSON格式，key为题目编号，value为答案', verbose_name='学生提交的答案'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submit_time',
            field=models.DateTimeField(auto_now_add=True, help_text='第一次提交的时间，用于防作弊检查', verbose_name='首次提交时间'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='total_scoreable',
            field=models.IntegerField(default=0, help_text='总题数减去未答题数，用于计算正确率', verbose_name='可判分总题数'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, help_text='最后一次提交或修改的时间', verbose_name='最后更新时间'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='wrong_count',
            field=models.IntegerField(default=0, help_text='学生答错的题目数量', verbose_name='答错题数'),
        ),
        migrations.AlterField(
            model_name='wrongquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='错题记录创建的时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='wrongquestion',
            name='exam',
            field=models.ForeignKey(help_text='这道错题来自哪张试卷', on_delete=django.db.models.deletion.CASCADE, to='exams.exam', verbose_name='来源试卷'),
        ),
        migrations.AlterField(
            model_name='wrongquestion',
            name='question',
            field=models.ForeignKey(help_text='答错的题目', on_delete=django.db.models.deletion.CASCADE, to='exams.question', verbose_name='题目'),
        ),
        migrations.AlterField(
            model_name='wrongquestion',
            name='student',
            field=models.ForeignKey(help_text='错题所属的学生', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='学生'),
        ),
        migrations.AlterField(
            model_name='wrongquestion',
            name='student_answer',
            field=models.JSONField(blank=True, default=dict, help_text='学生的错误答案，JSON格式', null=True, verbose_name='学生答案'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('exam', 'q_id')},
        ),
    ]
